### ISSUE TITLE
Persisting options

### ISSUE THREAD

**Issue by nilovelez** [amieiro/wp-polyglots-facilitator#10]
It would be great if selected options persisted between sessions.

As an example, that would save you from selecting input and output languages every time you use the app.

Cookies? Local storage?

**Comment by amieiro** [comment]
I have developed the solution to this issue (https://github.com/amieiro/wp-polyglots-facilitator/commit/f8dc0f754fefb813da7bd5c32eaecf88f0e863fd) and I have deployed it to the production site (https://wp-polyglots-facilitator.jesusamieiro.com/), so I close this issue.
