### ISSUE TITLE
Export the other element types

### ISSUE THREAD

**Issue by JaviRpo** [amieiro/wp-polyglots-facilitator#5]
The current functionality only exports the Themes and Plugins
![image](https://user-images.githubusercontent.com/8562436/83580263-2e62d200-a501-11ea-9bdb-75642abdc1d9.png)

It would be great if it also works for the other elements
![image](https://user-images.githubusercontent.com/8562436/83580322-610cca80-a501-11ea-9680-f93425d9d6c0.png)

**Comment by amieiro** [comment]
Hello @JaviRpo 

The main reason of this tool is translate WordPress and its ecosystem to Galician language, so I am focused on the elements that currently are not translated to Galician.

This week I have added the Android app translation and the next release will be focused on some element of the "Meta" zone.

Are you using the webtool to translate WordPress to some language? If you have some need, please, tell me about it, so I can take it in consideration for the next releases.

Best regards

**Comment by amieiro** [comment]
Hello @JaviRpo 

This weekend I have been working on the webapp and now supports all elements that you can translate in the official GlotPress, so I close this issue.

Best regards
